packages:
  - apps/*
  - libs/*

catalog:
  # React ecosystem
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.2.45
  "@types/react-dom": ^18.2.18

  # Express ecosystem
  express: ^4.18.2
  cors: ^2.8.5
  cookie-parser: ^1.4.6
  "@types/express": ^4.17.21
  "@types/cors": ^2.8.17
  "@types/cookie-parser": ^1.4.6

  # Database
  pg: ^8.11.3
  "@types/pg": ^8.10.9

  # Configuration & utilities
  dotenv: ^16.4.7
  clsx: ^2.1.0
  zustand: ^5.0.2

  # Astro ecosystem
  astro: ^4.16.18
  "@astrojs/react": ^3.6.2
  "@astrojs/tailwind": ^5.1.4
  "@astrojs/check": ^0.9.4

  # Styling
  tailwindcss: ^3.4.18

  # Build tools & TypeScript
  typescript: ^5.3.3
  tsx: ^4.7.0
  tsup: ^8.0.1
  "@types/node": ^20.10.5

overrides:
  astro@<5.14.3: ">=5.14.3"
  astro@<5.15.8: ">=5.15.8"
  astro@<5.15.9: ">=5.15.9"
  astro@<=5.15.6: ">=5.15.8"
  astro@>=2.16.0 <5.15.5: ">=5.15.5"
  electron@<35.7.5: ">=35.7.5"
  esbuild@<=0.24.2: ">=0.25.0"
